<?php

include "../../backend/config.php";

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="reports_' . date('Y-m-d_H-i-s') . '.xls"');
header('Cache-Control: max-age=0');

try {
    // Base query with joins
    $query = "SELECT 
                r.report_id,
                r.child_id,
                c.first_name,
                c.last_name,
                c.gender,
                c.birthdate,
                c.zone_id,
                z.zone_name,
                r.report_type,
                r.report_date,
                r.generated_by,
                td.full_name AS generated_by_name
              FROM tbl_report r
              LEFT JOIN tbl_child c ON r.child_id = c.child_id
              LEFT JOIN tbl_barangay z ON c.zone_id = z.zone_id
              LEFT JOIN tbl_user u ON r.generated_by = u.user_id
                LEFT JOIN tbl_user_details td ON u.user_id = td.user_id
              WHERE 1=1";
    
    $params = [];
    $types  = "";
    $values = [];

    // Apply filters
    if (!empty($_GET['report_type'])) {
        $query .= " AND r.report_type LIKE ?";
        $types  .= "s";
        $values[] = '%' . $_GET['report_type'] . '%';
    }

    if (!empty($_GET['zone'])) {
        $query .= " AND z.zone_id = ?";
        $types  .= "i";
        $values[] = $_GET['zone'];
    }


    if (!empty($_GET['start_date'])) {
        $query .= " AND DATE(r.report_date) >= ?";
        $types  .= "s";
        $values[] = $_GET['start_date'];
    }

    if (!empty($_GET['end_date'])) {
        $query .= " AND DATE(r.report_date) <= ?";
        $types  .= "s";
        $values[] = $_GET['end_date'];
    }

    $query .= " ORDER BY r.report_date DESC";

    // Prepare & bind
    $stmt = $conn->prepare($query);
    if ($types && $values) {
        $stmt->bind_param($types, ...$values);
    }
    $stmt->execute();
    $result = $stmt->get_result();
    $records = $result->fetch_all(MYSQLI_ASSOC);

    // Function to calculate age
    function calculateAge($birthdate) {
        if (!$birthdate) return 'N/A';
        $birth = new DateTime($birthdate);
        $today = new DateTime();
        return $birth->diff($today)->y;
    }

    // Start Excel output
    echo '<table border="1">';

    // Headers
    echo '<tr>';
    echo '<th>Report ID</th>';
    echo '<th>Report Code</th>';
    echo '<th>Child ID</th>';
    echo '<th>Child Name</th>';
    echo '<th>Gender</th>';
    echo '<th>Age</th>';
    echo '<th>Zone</th>';
    echo '<th>Report Type</th>';
    echo '<th>Generated By</th>';
    echo '<th>Report Date</th>';
    echo '</tr>';

    // Data rows
    foreach ($records as $record) {
        $age = calculateAge($record['birthdate']);
        $reportCode = '#RPT-' . str_pad($record['report_id'], 4, '0', STR_PAD_LEFT);

        echo '<tr>';
        echo '<td>' . htmlspecialchars($record['report_id']) . '</td>';
        echo '<td>' . htmlspecialchars($reportCode) . '</td>';
        echo '<td>' . htmlspecialchars($record['child_id']) . '</td>';
        echo '<td>' . htmlspecialchars($record['first_name'] . ' ' . $record['last_name']) . '</td>';
        echo '<td>' . htmlspecialchars($record['gender'] ?? 'N/A') . '</td>';
        echo '<td>' . htmlspecialchars($age) . '</td>';
        echo '<td>' . htmlspecialchars($record['zone_name'] ?? 'N/A') . '</td>';
        echo '<td>' . htmlspecialchars($record['report_type']) . '</td>';
        echo '<td>' . htmlspecialchars($record['generated_by_name']) . '</td>';
        echo '<td>' . htmlspecialchars(date('M d, Y H:i A', strtotime($record['report_date']))) . '</td>';
        echo '</tr>';
    }

    echo '</table>';

    // Summary information
    echo '<br><br>';
    echo '<table border="1">';
    echo '<tr><th colspan="2">Export Summary</th></tr>';
    echo '<tr><td>Total Records</td><td>' . count($records) . '</td></tr>';
    echo '<tr><td>Export Date</td><td>' . date('Y-m-d H:i:s') . '</td></tr>';

    if (!empty($_GET['report_type'])) {
        echo '<tr><td>Report Type Filter</td><td>' . htmlspecialchars($_GET['report_type']) . '</td></tr>';
    }
    if (!empty($_GET['zone'])) {
        echo '<tr><td>Zone Filter</td><td>' . htmlspecialchars($_GET['zone']) . '</td></tr>';
    }

    if (!empty($_GET['start_date'])) {
        echo '<tr><td>Start Date</td><td>' . htmlspecialchars($_GET['start_date']) . '</td></tr>';
    }
    if (!empty($_GET['end_date'])) {
        echo '<tr><td>End Date</td><td>' . htmlspecialchars($_GET['end_date']) . '</td></tr>';
    }

    echo '</table>';

} catch (Exception $e) {
    echo 'Error: ' . $e->getMessage();
} finally {
    $conn->close();
}
?>