<?php
// Include database connection
require_once '../../../config/database.php';

try {
    // Query to get all reports with related information
    $query = "
        SELECT 
            r.report_id,
            CONCAT('#RPT-', LPAD(r.report_id, 4, '0')) as report_number,
            r.child_id,
            c.first_name,
            c.last_name,
            c.birthdate,
            c.gender,
            z.zone_name,
            r.report_type,
            r.report_date,
            r.generated_by,
            ud.full_name as generated_by_name,
            ud.contact,
            ud.address
        FROM tbl_report r
        LEFT JOIN tbl_child c ON r.child_id = c.child_id
        LEFT JOIN tbl_zone z ON c.zone_id = z.zone_id
        LEFT JOIN tbl_user_details ud ON r.generated_by = ud.user_id
        ORDER BY r.report_date DESC
    ";
    
    $stmt = $pdo->prepare($query);
    $stmt->execute();
    $reports = $stmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Set headers for CSV download
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="reports_export_' . date('Y-m-d_H-i-s') . '.csv"');
    
    // Open output stream
    $output = fopen('php://output', 'w');
    
    // Write CSV headers
    $headers = [
        'Report ID',
        'Report Number', 
        'Child ID',
        'First Name',
        'Last Name',
        'Birth Date',
        'Age',
        'Gender',
        'Zone',
        'Report Type',
        'Report Date',
        'Generated By ID',
        'Generated By Name',
        'Contact',
        'Address'
    ];
    fputcsv($output, $headers);
    
    // Write data rows
    foreach ($reports as $report) {
        // Calculate age
        if ($report['birthdate']) {
            $birthDate = new DateTime($report['birthdate']);
            $today = new DateTime();
            $age = $today->diff($birthDate)->y;
        } else {
            $age = 'N/A';
        }
        
        $row = [
            $report['report_id'],
            $report['report_number'],
            $report['child_id'],
            $report['first_name'],
            $report['last_name'],
            $report['birthdate'] ? date('Y-m-d', strtotime($report['birthdate'])) : 'N/A',
            $age,
            $report['gender'] ?: 'N/A',
            $report['zone_name'] ?: 'N/A',
            $report['report_type'],
            date('Y-m-d H:i:s', strtotime($report['report_date'])),
            $report['generated_by'],
            $report['generated_by_name'] ?: 'System',
            $report['contact'] ?: 'N/A',
            $report['address'] ?: 'N/A'
        ];
        fputcsv($output, $row);
    }
    
    // Close output stream
    fclose($output);
    
} catch (Exception $e) {
    http_response_code(500);
    die('Error exporting reports: ' . $e->getMessage());
}
?>