<?php
include "../../backend/config.php";
session_start();

// Check if user is logged in and has admin role
if (!isset($_SESSION['user_id']) || $_SESSION["role_id"] != 2) {
    header("Location: ../components/login.php");
    exit();
}

// Set headers for Excel download
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="Medicine_Inventory_' . date('Y-m-d_H-i-s') . '.xls"');
header('Cache-Control: max-age=0');

// Start output buffering
ob_start();

try {
    // Get all medicines with comprehensive data
    $query = "SELECT 
        m.medicine_id,
        m.medicine_name,
        m.brand,
        m.generic_name,
        m.dosage_form,
        m.strength,
        m.unit,
        m.stock_quantity,
        m.minimum_stock,
        m.unit_cost,
        m.expiry_date,
        m.batch_number,
        m.supplier,
        m.description,
        m.status,
        m.created_at,
        m.updated_at,
        CASE 
            WHEN m.stock_quantity <= 0 THEN 'Out of Stock'
            WHEN m.stock_quantity <= m.minimum_stock THEN 'Low Stock'
            WHEN m.stock_quantity <= (m.minimum_stock * 1.5) THEN 'Normal'
            ELSE 'Good Stock'
        END as stock_status,
        CASE 
            WHEN m.expiry_date IS NULL THEN 'No Expiry'
            WHEN m.expiry_date < CURDATE() THEN 'Expired'
            WHEN DATEDIFF(m.expiry_date, CURDATE()) <= 30 THEN 'Expiring Soon'
            WHEN DATEDIFF(m.expiry_date, CURDATE()) <= 90 THEN 'Check Expiry'
            ELSE 'Good'
        END as expiry_status,
        CASE 
            WHEN m.expiry_date IS NULL THEN NULL
            ELSE DATEDIFF(m.expiry_date, CURDATE())
        END as days_until_expiry,
        (m.stock_quantity * COALESCE(m.unit_cost, 0)) as total_value
    FROM tbl_medicine m
    ORDER BY m.medicine_name ASC";

    $stmt = $conn->prepare($query);
    $stmt->execute();
    $result = $stmt->get_result();
    $medicines = $result->fetch_all(MYSQLI_ASSOC);

    // Calculate summary statistics
    $total_medicines = count($medicines);
    $total_value = array_sum(array_column($medicines, 'total_value'));
    $low_stock_count = count(array_filter($medicines, function($m) { 
        return in_array($m['stock_status'], ['Low Stock', 'Out of Stock']); 
    }));
    $expired_count = count(array_filter($medicines, function($m) { 
        return $m['expiry_status'] === 'Expired'; 
    }));
    $expiring_soon_count = count(array_filter($medicines, function($m) { 
        return $m['expiry_status'] === 'Expiring Soon'; 
    }));

    // Generate Excel content
    echo '<html>';
    echo '<head>';
    echo '<meta charset="UTF-8">';
    echo '<style>';
    echo 'table { border-collapse: collapse; width: 100%; font-family: Arial, sans-serif; }';
    echo 'th, td { border: 1px solid #000; padding: 8px; text-align: left; }';
    echo 'th { background-color: #2d5a3d; color: white; font-weight: bold; }';
    echo '.summary-table th { background-color: #4a7c59; }';
    echo '.center { text-align: center; }';
    echo '.currency { text-align: right; }';
    echo '.status-active { background-color: #d4edda; }';
    echo '.status-inactive { background-color: #f8f9fa; }';
    echo '.status-expired { background-color: #f8d7da; }';
    echo '.stock-low { background-color: #fff3cd; }';
    echo '.stock-critical { background-color: #f8d7da; }';
    echo '</style>';
    echo '</head>';
    echo '<body>';

    // Report Header
    echo '<h1 style="color: #2d5a3d; text-align: center;">Medicine Inventory Report</h1>';
    echo '<p style="text-align: center;">Generated on: ' . date('F d, Y - H:i:s') . '</p>';
    echo '<p style="text-align: center;">Generated by: Admin User</p>';
    echo '<hr>';

    // Summary Statistics
    echo '<h2 style="color: #2d5a3d;">Summary Statistics</h2>';
    echo '<table class="summary-table" style="width: 50%; margin-bottom: 20px;">';
    echo '<tr><th>Metric</th><th>Value</th></tr>';
    echo '<tr><td>Total Medicines</td><td class="center">' . $total_medicines . '</td></tr>';
    echo '<tr><td>Total Inventory Value</td><td class="currency">₱' . number_format($total_value, 2) . '</td></tr>';
    echo '<tr><td>Low Stock Items</td><td class="center">' . $low_stock_count . '</td></tr>';
    echo '<tr><td>Expired Items</td><td class="center">' . $expired_count . '</td></tr>';
    echo '<tr><td>Items Expiring Soon (30 days)</td><td class="center">' . $expiring_soon_count . '</td></tr>';
    echo '</table>';

    // Detailed Medicine Inventory
    echo '<h2 style="color: #2d5a3d;">Detailed Medicine Inventory</h2>';
    echo '<table>';
    echo '<thead>';
    echo '<tr>';
    echo '<th>ID</th>';
    echo '<th>Medicine Name</th>';
    echo '<th>Brand</th>';
    echo '<th>Generic Name</th>';
    echo '<th>Form</th>';
    echo '<th>Strength</th>';
    echo '<th>Unit</th>';
    echo '<th>Current Stock</th>';
    echo '<th>Minimum Stock</th>';
    echo '<th>Stock Status</th>';
    echo '<th>Unit Cost</th>';
    echo '<th>Total Value</th>';
    echo '<th>Expiry Date</th>';
    echo '<th>Days Until Expiry</th>';
    echo '<th>Expiry Status</th>';
    echo '<th>Batch Number</th>';
    echo '<th>Supplier</th>';
    echo '<th>Status</th>';
    echo '<th>Created</th>';
    echo '<th>Last Updated</th>';
    echo '</tr>';
    echo '</thead>';
    echo '<tbody>';

    foreach ($medicines as $medicine) {
        // Determine row styling based on status
        $row_class = '';
        if ($medicine['status'] === 'Expired' || $medicine['expiry_status'] === 'Expired') {
            $row_class = 'status-expired';
        } elseif ($medicine['stock_status'] === 'Low Stock' || $medicine['stock_status'] === 'Out of Stock') {
            $row_class = 'stock-low';
        } elseif ($medicine['status'] === 'Inactive') {
            $row_class = 'status-inactive';
        } elseif ($medicine['status'] === 'Active') {
            $row_class = 'status-active';
        }

        echo '<tr class="' . $row_class . '">';
        echo '<td class="center">' . $medicine['medicine_id'] . '</td>';
        echo '<td>' . htmlspecialchars($medicine['medicine_name']) . '</td>';
        echo '<td>' . htmlspecialchars($medicine['brand'] ?: '-') . '</td>';
        echo '<td>' . htmlspecialchars($medicine['generic_name'] ?: '-') . '</td>';
        echo '<td>' . htmlspecialchars($medicine['dosage_form'] ?: '-') . '</td>';
        echo '<td>' . htmlspecialchars($medicine['strength'] ?: '-') . '</td>';
        echo '<td>' . htmlspecialchars($medicine['unit'] ?: '-') . '</td>';
        echo '<td class="center">' . number_format($medicine['stock_quantity'], 2) . '</td>';
        echo '<td class="center">' . number_format($medicine['minimum_stock'], 2) . '</td>';
        echo '<td class="center">' . $medicine['stock_status'] . '</td>';
        echo '<td class="currency">₱' . number_format($medicine['unit_cost'], 2) . '</td>';
        echo '<td class="currency">₱' . number_format($medicine['total_value'], 2) . '</td>';
        echo '<td class="center">' . ($medicine['expiry_date'] ? date('M d, Y', strtotime($medicine['expiry_date'])) : 'No Expiry') . '</td>';
        echo '<td class="center">' . ($medicine['days_until_expiry'] !== null ? $medicine['days_until_expiry'] . ' days' : 'N/A') . '</td>';
        echo '<td class="center">' . $medicine['expiry_status'] . '</td>';
        echo '<td>' . htmlspecialchars($medicine['batch_number'] ?: '-') . '</td>';
        echo '<td>' . htmlspecialchars($medicine['supplier'] ?: '-') . '</td>';
        echo '<td class="center">' . $medicine['status'] . '</td>';
        echo '<td class="center">' . date('M d, Y', strtotime($medicine['created_at'])) . '</td>';
        echo '<td class="center">' . date('M d, Y H:i', strtotime($medicine['updated_at'])) . '</td>';
        echo '</tr>';
    }

    echo '</tbody>';
    echo '</table>';

    // Stock Status Summary
    echo '<br><h2 style="color: #2d5a3d;">Stock Status Breakdown</h2>';
    $stock_summary = [];
    foreach ($medicines as $medicine) {
        $status = $medicine['stock_status'];
        if (!isset($stock_summary[$status])) {
            $stock_summary[$status] = 0;
        }
        $stock_summary[$status]++;
    }

    echo '<table class="summary-table" style="width: 40%; margin-bottom: 20px;">';
    echo '<tr><th>Stock Status</th><th>Count</th><th>Percentage</th></tr>';
    foreach ($stock_summary as $status => $count) {
        $percentage = ($count / $total_medicines) * 100;
        echo '<tr>';
        echo '<td>' . $status . '</td>';
        echo '<td class="center">' . $count . '</td>';
        echo '<td class="center">' . number_format($percentage, 1) . '%</td>';
        echo '</tr>';
    }
    echo '</table>';

    // Expiry Status Summary
    echo '<h2 style="color: #2d5a3d;">Expiry Status Breakdown</h2>';
    $expiry_summary = [];
    foreach ($medicines as $medicine) {
        $status = $medicine['expiry_status'];
        if (!isset($expiry_summary[$status])) {
            $expiry_summary[$status] = 0;
        }
        $expiry_summary[$status]++;
    }

    echo '<table class="summary-table" style="width: 40%; margin-bottom: 20px;">';
    echo '<tr><th>Expiry Status</th><th>Count</th><th>Percentage</th></tr>';
    foreach ($expiry_summary as $status => $count) {
        $percentage = ($count / $total_medicines) * 100;
        echo '<tr>';
        echo '<td>' . $status . '</td>';
        echo '<td class="center">' . $count . '</td>';
        echo '<td class="center">' . number_format($percentage, 1) . '%</td>';
        echo '</tr>';
    }
    echo '</table>';

    // Critical Alerts Section
    echo '<h2 style="color: #dc3545;">Critical Alerts</h2>';
    
    // Expired medicines
    $expired_medicines = array_filter($medicines, function($m) { 
        return $m['expiry_status'] === 'Expired'; 
    });
    
    if (!empty($expired_medicines)) {
        echo '<h3 style="color: #dc3545;">Expired Medicines (' . count($expired_medicines) . ')</h3>';
        echo '<table style="width: 80%; margin-bottom: 15px;">';
        echo '<tr><th>Medicine Name</th><th>Stock</th><th>Expiry Date</th><th>Days Overdue</th></tr>';
        foreach ($expired_medicines as $medicine) {
            echo '<tr class="status-expired">';
            echo '<td>' . htmlspecialchars($medicine['medicine_name']) . '</td>';
            echo '<td class="center">' . number_format($medicine['stock_quantity'], 2) . ' ' . $medicine['unit'] . '</td>';
            echo '<td class="center">' . date('M d, Y', strtotime($medicine['expiry_date'])) . '</td>';
            echo '<td class="center">' . abs($medicine['days_until_expiry']) . ' days</td>';
            echo '</tr>';
        }
        echo '</table>';
    }

    // Low stock medicines
    $low_stock_medicines = array_filter($medicines, function($m) { 
        return in_array($m['stock_status'], ['Low Stock', 'Out of Stock']); 
    });
    
    if (!empty($low_stock_medicines)) {
        echo '<h3 style="color: #ffc107;">Low Stock Medicines (' . count($low_stock_medicines) . ')</h3>';
        echo '<table style="width: 80%; margin-bottom: 15px;">';
        echo '<tr><th>Medicine Name</th><th>Current Stock</th><th>Minimum Stock</th><th>Status</th></tr>';
        foreach ($low_stock_medicines as $medicine) {
            echo '<tr class="stock-low">';
            echo '<td>' . htmlspecialchars($medicine['medicine_name']) . '</td>';
            echo '<td class="center">' . number_format($medicine['stock_quantity'], 2) . ' ' . $medicine['unit'] . '</td>';
            echo '<td class="center">' . number_format($medicine['minimum_stock'], 2) . ' ' . $medicine['unit'] . '</td>';
            echo '<td class="center">' . $medicine['stock_status'] . '</td>';
            echo '</tr>';
        }
        echo '</table>';
    }

    // Footer
    echo '<hr>';
    echo '<p style="text-align: center; font-size: 12px; color: #666;">Medicine Inventory Management System - Generated ' . date('Y-m-d H:i:s') . '</p>';
    echo '<p style="text-align: center; font-size: 12px; color: #666;">This report contains ' . $total_medicines . ' medicine records with a total inventory value of ₱' . number_format($total_value, 2) . '</p>';

    echo '</body>';
    echo '</html>';

} catch (PDOException $e) {
    // Clear any previous output
    ob_clean();
    
    // Set headers for HTML error page instead of Excel
    header('Content-Type: text/html');
    header('Content-Disposition: inline');
    
    echo '<html><body>';
    echo '<h1>Export Error</h1>';
    echo '<p>An error occurred while generating the medicine inventory report:</p>';
    echo '<p><strong>Error:</strong> ' . htmlspecialchars($e->getMessage()) . '</p>';
    echo '<p><a href="javascript:history.back()">Go Back</a></p>';
    echo '</body></html>';
} catch (Exception $e) {
    // Clear any previous output
    ob_clean();
    
    // Set headers for HTML error page instead of Excel
    header('Content-Type: text/html');
    header('Content-Disposition: inline');
    
    echo '<html><body>';
    echo '<h1>Export Error</h1>';
    echo '<p>An unexpected error occurred:</p>';
    echo '<p><strong>Error:</strong> ' . htmlspecialchars($e->getMessage()) . '</p>';
    echo '<p><a href="javascript:history.back()">Go Back</a></p>';
    echo '</body></html>';
}

// End output buffering and send content
ob_end_flush();
?>